// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureNextButton(arg1) {
  return window['go']['main']['App']['CaptureNextButton'](arg1);
}

export function DashCreateLayout(arg1) {
  return window['go']['main']['App']['DashCreateLayout'](arg1);
}

export function DashCyclePage(arg1) {
  return window['go']['main']['App']['DashCyclePage'](arg1);
}

export function DashDeleteLayout(arg1) {
  return window['go']['main']['App']['DashDeleteLayout'](arg1);
}

export function DashGetPreview(arg1) {
  return window['go']['main']['App']['DashGetPreview'](arg1);
}

export function DashListLayouts() {
  return window['go']['main']['App']['DashListLayouts']();
}

export function DashLoadLayoutByID(arg1) {
  return window['go']['main']['App']['DashLoadLayoutByID'](arg1);
}

export function DashSaveLayout(arg1) {
  return window['go']['main']['App']['DashSaveLayout'](arg1);
}

export function DashSetDefault(arg1) {
  return window['go']['main']['App']['DashSetDefault'](arg1);
}

export function DeviceAdd(arg1) {
  return window['go']['main']['App']['DeviceAdd'](arg1);
}

export function DeviceGetCatalog() {
  return window['go']['main']['App']['DeviceGetCatalog']();
}

export function DeviceGetDeviceBindings(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeviceGetDeviceBindings'](arg1, arg2, arg3);
}

export function DeviceGetDevicePaused(arg1) {
  return window['go']['main']['App']['DeviceGetDevicePaused'](arg1);
}

export function DeviceGetSavedDevices() {
  return window['go']['main']['App']['DeviceGetSavedDevices']();
}

export function DeviceGetScreenStatus() {
  return window['go']['main']['App']['DeviceGetScreenStatus']();
}

export function DeviceRemoveDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeviceRemoveDevice'](arg1, arg2, arg3);
}

export function DeviceRenameDevice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceRenameDevice'](arg1, arg2, arg3, arg4);
}

export function DeviceSaveDeviceBindings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceSaveDeviceBindings'](arg1, arg2, arg3, arg4);
}

export function DeviceSetDashLayout(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceSetDashLayout'](arg1, arg2, arg3, arg4);
}

export function DeviceSetDevicePaused(arg1, arg2) {
  return window['go']['main']['App']['DeviceSetDevicePaused'](arg1, arg2);
}

export function DeviceSetScreenOffset(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeviceSetScreenOffset'](arg1, arg2, arg3, arg4, arg5);
}

export function DeviceSetScreenRotation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceSetScreenRotation'](arg1, arg2, arg3, arg4);
}

export function GetBindings() {
  return window['go']['main']['App']['GetBindings']();
}

export function GetBuildChannel() {
  return window['go']['main']['App']['GetBuildChannel']();
}

export function GetCommandCatalog() {
  return window['go']['main']['App']['GetCommandCatalog']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWidgetCatalog() {
  return window['go']['main']['App']['GetWidgetCatalog']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SaveBindings(arg1) {
  return window['go']['main']['App']['SaveBindings'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}
