// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {devices} from '../models';
import {setup} from '../models';

export function DeviceDelete(arg1:string):Promise<void>;

export function DeviceGetAll():Promise<Array<devices.DeviceConfig>>;

export function DeviceListKnownModels():Promise<Array<devices.WheelModel>>;

export function DeviceListPorts():Promise<Array<devices.DetectedPort>>;

export function DeviceSave(arg1:devices.DeviceConfig):Promise<devices.DeviceConfig>;

export function IsConnected():Promise<boolean>;

export function SetupDelete(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetupListAll():Promise<Array<setup.Setup>>;

export function SetupSave(arg1:setup.Setup):Promise<setup.Setup>;
