// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureNextButton(arg1) {
  return window['go']['main']['App']['CaptureNextButton'](arg1);
}

export function DashCreateLayout(arg1) {
  return window['go']['main']['App']['DashCreateLayout'](arg1);
}

export function DashCyclePage(arg1) {
  return window['go']['main']['App']['DashCyclePage'](arg1);
}

export function DashDeleteLayout(arg1) {
  return window['go']['main']['App']['DashDeleteLayout'](arg1);
}

export function DashGetPreview(arg1) {
  return window['go']['main']['App']['DashGetPreview'](arg1);
}

export function DashListLayouts() {
  return window['go']['main']['App']['DashListLayouts']();
}

export function DashLoadLayout() {
  return window['go']['main']['App']['DashLoadLayout']();
}

export function DashLoadLayoutByID(arg1) {
  return window['go']['main']['App']['DashLoadLayoutByID'](arg1);
}

export function DashSaveLayout(arg1) {
  return window['go']['main']['App']['DashSaveLayout'](arg1);
}

export function DashSetDefault(arg1) {
  return window['go']['main']['App']['DashSetDefault'](arg1);
}

export function DeviceGetDeviceBindings(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeviceGetDeviceBindings'](arg1, arg2, arg3);
}

export function DeviceGetSavedScreens() {
  return window['go']['main']['App']['DeviceGetSavedScreens']();
}

export function DeviceGetScreen() {
  return window['go']['main']['App']['DeviceGetScreen']();
}

export function DeviceGetScreenPaused() {
  return window['go']['main']['App']['DeviceGetScreenPaused']();
}

export function DeviceGetScreenStatus() {
  return window['go']['main']['App']['DeviceGetScreenStatus']();
}

export function DeviceRenameScreen(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceRenameScreen'](arg1, arg2, arg3, arg4);
}

export function DeviceSaveDeviceBindings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceSaveDeviceBindings'](arg1, arg2, arg3, arg4);
}

export function DeviceScanScreens() {
  return window['go']['main']['App']['DeviceScanScreens']();
}

export function DeviceSelectScreen(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DeviceSelectScreen'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeviceSetDashLayout(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceSetDashLayout'](arg1, arg2, arg3, arg4);
}

export function DeviceSetScreenPaused(arg1) {
  return window['go']['main']['App']['DeviceSetScreenPaused'](arg1);
}

export function DeviceSetScreenRotation(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeviceSetScreenRotation'](arg1, arg2, arg3, arg4);
}

export function GetBindings() {
  return window['go']['main']['App']['GetBindings']();
}

export function GetBuildChannel() {
  return window['go']['main']['App']['GetBuildChannel']();
}

export function GetCommandCatalog() {
  return window['go']['main']['App']['GetCommandCatalog']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWidgetCatalog() {
  return window['go']['main']['App']['GetWidgetCatalog']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SaveBindings(arg1) {
  return window['go']['main']['App']['SaveBindings'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
  return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}
