// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DashLoadLayout() {
  return window['go']['main']['App']['DashLoadLayout']();
}

export function DashSaveLayout(arg1) {
  return window['go']['main']['App']['DashSaveLayout'](arg1);
}

export function DeviceDelete(arg1) {
  return window['go']['main']['App']['DeviceDelete'](arg1);
}

export function DeviceGetAll() {
  return window['go']['main']['App']['DeviceGetAll']();
}

export function DeviceListKnownModels() {
  return window['go']['main']['App']['DeviceListKnownModels']();
}

export function DeviceListPorts() {
  return window['go']['main']['App']['DeviceListPorts']();
}

export function DeviceSave(arg1) {
  return window['go']['main']['App']['DeviceSave'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function SetupDelete(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetupDelete'](arg1, arg2, arg3);
}

export function SetupListAll() {
  return window['go']['main']['App']['SetupListAll']();
}

export function SetupSave(arg1) {
  return window['go']['main']['App']['SetupSave'](arg1);
}

export function VoCoreGetSelected() {
  return window['go']['main']['App']['VoCoreGetSelected']();
}

export function VoCoreScanScreens() {
  return window['go']['main']['App']['VoCoreScanScreens']();
}

export function VoCoreSelectScreen(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['VoCoreSelectScreen'](arg1, arg2, arg3, arg4);
}
