// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {dashboard} from '../models';
import {widgets} from '../models';
import {devices} from '../models';
import {alerts} from '../models';
import {input} from '../models';
import {commands} from '../models';
import {settings} from '../models';

export function CaptureNextButton(arg1:number):Promise<number>;

export function CheckUpdate():Promise<updater.ReleaseInfo>;

export function DashCreateLayout(arg1:string):Promise<dashboard.DashLayout>;

export function DashCyclePage(arg1:number):Promise<void>;

export function DashDeleteLayout(arg1:string):Promise<void>;

export function DashGetDefaultDomainPalette():Promise<widgets.DomainPalette>;

export function DashGetDefaultFormatPreferences():Promise<widgets.FormatPreferences>;

export function DashGetDefaultTheme():Promise<widgets.DashTheme>;

export function DashGetGlobalSettings():Promise<dashboard.GlobalDashSettings>;

export function DashGetPreview(arg1:string):Promise<string>;

export function DashListLayouts():Promise<Array<dashboard.LayoutMeta>>;

export function DashLoadLayoutByID(arg1:string):Promise<dashboard.DashLayout>;

export function DashSaveGlobalSettings(arg1:dashboard.GlobalDashSettings):Promise<void>;

export function DashSaveLayout(arg1:dashboard.DashLayout):Promise<void>;

export function DashSetDefault(arg1:string):Promise<void>;

export function DashStartPreview(arg1:dashboard.DashLayout,arg2:number,arg3:boolean):Promise<void>;

export function DashStopPreview():Promise<void>;

export function DashUpdatePreview(arg1:dashboard.DashLayout,arg2:number,arg3:boolean):Promise<void>;

export function DeviceAdd(arg1:string):Promise<void>;

export function DeviceAddScanned(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function DeviceGetCatalog():Promise<Array<devices.CatalogEntry>>;

export function DeviceGetDeviceBindings(arg1:number,arg2:number,arg3:string):Promise<Array<devices.DeviceBinding>>;

export function DeviceGetDeviceDisabled(arg1:string):Promise<boolean>;

export function DeviceGetSavedDevices():Promise<Array<devices.SavedDevice>>;

export function DeviceGetScreenStatus():Promise<string>;

export function DeviceRemoveDevice(arg1:number,arg2:number,arg3:string):Promise<void>;

export function DeviceRenameDevice(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function DeviceSaveDeviceBindings(arg1:number,arg2:number,arg3:string,arg4:Array<devices.DeviceBinding>):Promise<void>;

export function DeviceScanUnregistered(arg1:string):Promise<Array<devices.DetectedScreen>>;

export function DeviceSelectCaptureRegion(arg1:number,arg2:number,arg3:string):Promise<void>;

export function DeviceSetDashLayout(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function DeviceSetDeviceDisabled(arg1:string,arg2:boolean):Promise<void>;

export function DeviceSetPurpose(arg1:number,arg2:number,arg3:string,arg4:devices.DevicePurpose):Promise<void>;

export function DeviceSetPurposeConfig(arg1:number,arg2:number,arg3:string,arg4:Array<number>):Promise<void>;

export function DeviceSetScreenOffset(arg1:number,arg2:number,arg3:string,arg4:number,arg5:number,arg6:number):Promise<void>;

export function DeviceSetScreenRotation(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function DownloadAndInstall(arg1:string):Promise<void>;

export function GetAlertCatalog():Promise<Array<alerts.AlertMeta>>;

export function GetBindings():Promise<input.Config>;

export function GetBuildChannel():Promise<string>;

export function GetCommandCatalog():Promise<Array<commands.CommandMeta>>;

export function GetSettings():Promise<settings.Settings>;

export function GetVersion():Promise<string>;

export function GetWidgetCatalog():Promise<Array<widgets.WidgetMeta>>;

export function GetWidgetPreview(arg1:string,arg2:number,arg3:number):Promise<string>;

export function InstallScreenDriver(arg1:string):Promise<void>;

export function IsConnected():Promise<boolean>;

export function SaveBindings(arg1:input.Config):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;
