// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dashboard} from '../models';
import {devices} from '../models';
import {input} from '../models';
import {commands} from '../models';
import {widgets} from '../models';

export function CaptureNextButton(arg1:number):Promise<number>;

export function DashCreateLayout(arg1:string):Promise<dashboard.DashLayout>;

export function DashCyclePage(arg1:number):Promise<void>;

export function DashDeleteLayout(arg1:string):Promise<void>;

export function DashGetPreview(arg1:string):Promise<string>;

export function DashListLayouts():Promise<Array<dashboard.LayoutMeta>>;

export function DashLoadLayout():Promise<dashboard.DashLayout>;

export function DashLoadLayoutByID(arg1:string):Promise<dashboard.DashLayout>;

export function DashSaveLayout(arg1:dashboard.DashLayout):Promise<void>;

export function DashSetDefault(arg1:string):Promise<void>;

export function DeviceGetDeviceBindings(arg1:number,arg2:number,arg3:string):Promise<Array<devices.DeviceBinding>>;

export function DeviceGetSavedScreens():Promise<Array<devices.SavedScreen>>;

export function DeviceGetScreen():Promise<devices.SavedScreen>;

export function DeviceGetScreenPaused():Promise<boolean>;

export function DeviceGetScreenStatus():Promise<string>;

export function DeviceRenameScreen(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function DeviceSaveDeviceBindings(arg1:number,arg2:number,arg3:string,arg4:Array<devices.DeviceBinding>):Promise<void>;

export function DeviceScanScreens():Promise<Array<devices.DetectedScreen>>;

export function DeviceSelectScreen(arg1:number,arg2:number,arg3:string,arg4:number,arg5:number,arg6:string):Promise<void>;

export function DeviceSetDashLayout(arg1:number,arg2:number,arg3:string,arg4:string):Promise<void>;

export function DeviceSetScreenPaused(arg1:boolean):Promise<void>;

export function DeviceSetScreenRotation(arg1:number,arg2:number,arg3:string,arg4:number):Promise<void>;

export function GetBindings():Promise<input.Config>;

export function GetBuildChannel():Promise<string>;

export function GetCommandCatalog():Promise<Array<commands.CommandMeta>>;

export function GetVersion():Promise<string>;

export function GetWidgetCatalog():Promise<Array<widgets.WidgetMeta>>;

export function IsConnected():Promise<boolean>;

export function SaveBindings(arg1:input.Config):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMaximise():Promise<void>;

export function WindowMinimise():Promise<void>;
