// Wails runtime bindings wrapper.
// The wailsjs/ directory is auto-generated by `wails dev` or `wails generate module`.
// This file re-exports the typed API surface used by the frontend.
// Run `wails dev` once to generate the wailsjs/ directory, then update these imports.

// ── Runtime helpers ───────────────────────────────────────────────────────

/**
 * Emits a Wails event to the backend.
 * Wraps `window.runtime.EventsEmit` with a typed signature.
 */
export function emitEvent(event: string, data?: unknown): void {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ;(window as any).runtime?.EventsEmit(event, data)
}

/**
 * Subscribes to a Wails event from the backend.
 * Returns an unsubscribe function.
 */
export function onEvent(event: string, callback: (data: unknown) => void): () => void {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  ;(window as any).runtime?.EventsOn(event, callback)
  return () => {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ;(window as any).runtime?.EventsOff(event)
  }
}

// ── Go binding stubs ───────────────────────────────────────────────────────
// After `wails dev` generates wailsjs/go/main/App.js, replace these stubs
// with real imports:
//   import { GetSetups, SaveSetup } from '../../wailsjs/go/main/App'

export const WailsAPI = {
  /** Placeholder — will be replaced by generated binding */
  getSetups: async (): Promise<unknown[]> => [],
  saveSetup: async (_setup: unknown): Promise<void> => {},
}
